name: NGS_Aarhus
  - conda-forge
  - plotly
  - defaults
  - bioconda
  - anaconda
  - grst
dependencies:
  - bioconductor-edger==3.36
  - gsl
  - scanpy
  - python-igraph
  - leidenalg
  - ipykernel
  - scvelo
  - python-annoy
  - multicore-tsne
  - matplotlib
  - pytables
  - plotly
  - nbformat
  - star==2.7.10a
  - bcftools
  - scikit-allel
  - bioconda::fastqc
  - multiqc
  - qualimap
  - minimap2
  - samtools
  - r-base==4.1.2
  - r-dplyr
  - r-vcfr
  - r-formattable
  - r-venndiagram
  - r-irkernel
  - r-pheatmap
  - bioconductor-mixomics
  - vcftools
  - gffread
  - pip
  - pip:
    - batchglm==0.7.4
    - bbknn==1.5.1
    - cython==0.29.30
    - diffxpy==0.7.4
    - imageio==2.19.2
    - pywavelets==1.3.0
    - robustbase==0.2.8
    - scikit-image==0.19.2
    - scrublet==0.2.3
    - sparse==0.13.0
    - tifffile==2022.5.4
    - charset-normalizer==2.0.12
    - colorama==0.4.4
    - idna==3.3
    - pycparser==2.21
    - pyopenssl==22.0.0
    - requests==2.27.1
    - six==1.16.0
    - tqdm==4.64.0
    - urllib3==1.26.9
    - wheel==0.37.1
